#!/bin/bash

echo "=========================================="
echo "SLAM超时与状态反馈修复测试"
echo "=========================================="
echo ""

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${YELLOW}本次修复内容${NC}"
echo "1. 增加SLAM配置超时时间：5秒 → 15秒"
echo "2. 其他lifecycle操作超时：5秒 → 10秒"
echo "3. 前端添加20秒超时保护，防止卡在'切换中'"
echo "4. 增强调试日志，追踪消息流向"
echo ""

# 步骤1
echo -e "${BLUE}步骤1: 准备测试环境${NC}"
echo "=========================================="
echo "1. 确保机器人已启动（ros2 launch cleanbot_control cleanbot.launch.py）"
echo "2. 确保导航节点已启动"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤2
echo -e "${BLUE}步骤2: 打开浏览器并强制刷新${NC}"
echo "=========================================="
echo "1. 打开：http://localhost:8080"
echo "2. ${RED}重要${NC}: 按 ${YELLOW}Ctrl + Shift + R${NC} 强制刷新（版本已更新到v6）"
echo "3. 按 ${YELLOW}F12${NC} 打开控制台"
echo ""
echo "检查版本号："
echo "  - 在控制台的Network标签中，查看control.js的URL"
echo "  - 应该显示：${GREEN}control.js?v=20251215-6${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤3
echo -e "${BLUE}步骤3: 测试正常启动SLAM${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 确保当前在${YELLOW}手动模式${NC}"
echo "  2) 点击${YELLOW}建图${NC}按钮"
echo "  3) 观察状态变化（需要10-15秒）"
echo ""
echo "预期的${GREEN}正常${NC}情况："
echo ""
echo "前端界面："
echo "  ${YELLOW}⏳ 切换中...${NC}  （立即显示）"
echo "  ⬇️ （等待10-15秒）"
echo "  ${GREEN}✅ 就绪${NC}  （配置完成）"
echo ""
echo "浏览器控制台："
echo "  ${GREEN}[导航调试] 收到导航信息: slam_activating${NC}"
echo "  ${GREEN}[导航调试] 收到导航信息: mode_changed:mapping${NC}"
echo ""
echo "后端日志（终端）："
echo "  ${GREEN}[navigation_mode_manager]: 正在配置SLAM节点（可能需要10-15秒）...${NC}"
echo "  ${GREEN}[slam_toolbox]: Configuring${NC}"
echo "  ${GREEN}[slam_toolbox]: Using solver plugin...${NC}"
echo "  ${GREEN}[navigation_mode_manager]: ✅ SLAM配置成功${NC}"
echo "  ${GREEN}[navigation_mode_manager]: ✅ SLAM节点已激活${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤4
echo -e "${BLUE}步骤4: 观察后端详细日志${NC}"
echo "=========================================="
echo ""
echo "在机器人终端，查找以下日志："
echo ""
echo "${GREEN}成功情况${NC}应该显示："
echo "  [navigation_mode_manager]: 激活SLAM节点..."
echo "  [navigation_mode_manager]: 正在配置SLAM节点（可能需要10-15秒）..."
echo "  [slam_toolbox]: Configuring"
echo "  [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver"
echo "  [navigation_mode_manager]: ✅ 状态切换成功: /slam_toolbox/change_state"
echo "  [navigation_mode_manager]: ✅ SLAM配置成功"
echo "  [navigation_mode_manager]: 正在激活SLAM节点..."
echo "  [navigation_mode_manager]: ✅ 状态切换成功: /slam_toolbox/change_state"
echo "  [navigation_mode_manager]: ✅ SLAM节点已激活"
echo ""
echo "${RED}失败情况${NC}（超过15秒）会显示："
echo "  [navigation_mode_manager]: ❌ 状态切换超时(15秒): /slam_toolbox/change_state"
echo "  [navigation_mode_manager]: ❌ SLAM配置失败"
echo "  [navigation_mode_manager]: 已发布失败消息: mode_failed:SLAM配置失败或超时"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤5
echo -e "${BLUE}步骤5: 测试前端超时保护${NC}"
echo "=========================================="
echo ""
echo "这个测试验证：如果后端消息丢失，前端不会卡住"
echo ""
echo "操作："
echo "  1) 切换到建图模式"
echo "  2) 如果看到'⏳ 切换中...'超过20秒"
echo "  3) 前端应该自动显示'❌ 切换超时'"
echo ""
echo "预期结果："
echo "  ⏳ 切换中... （持续20秒）"
echo "  ⬇️"
echo "  ${RED}❌ 切换超时${NC}"
echo "  ⬇️ （3秒后）"
echo "  ${GREEN}✅ 就绪${NC}"
echo ""
echo "控制台输出："
echo "  ${RED}❌ 模式切换超时（20秒未响应），可能是节点启动时间过长${NC}"
echo ""
echo "注意：正常情况下${GREEN}不应该${NC}触发这个超时，因为："
echo "  - 后端最长15秒"
echo "  - 前端20秒超时 > 后端15秒"
echo "  - 只有在极端情况（WebSocket断线等）才会触发"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤6
echo -e "${BLUE}步骤6: 测试失败状态反馈${NC}"
echo "=========================================="
echo ""
echo "如果SLAM真的配置失败（比如配置文件错误），验证失败反馈："
echo ""
echo "预期结果："
echo "  前端界面："
echo "    ⏳ 切换中... → ${RED}❌ 切换失败${NC} → （3秒后） ${GREEN}✅ 就绪${NC}"
echo ""
echo "  控制台："
echo "    ${RED}[导航调试] 收到导航信息: mode_failed:SLAM配置失败或超时${NC}"
echo "    ${RED}[导航调试] 模式切换失败: SLAM配置失败或超时${NC}"
echo ""
echo "  后端日志："
echo "    ${RED}[navigation_mode_manager]: ❌ SLAM配置失败${NC}"
echo "    ${RED}[navigation_mode_manager]: 已发布失败消息: mode_failed:...${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤7
echo -e "${BLUE}步骤7: 检查lifecycle状态${NC}"
echo "=========================================="
echo ""
echo "使用ROS2命令检查SLAM节点状态："
echo ""
echo -e "${YELLOW}ros2 lifecycle get /slam_toolbox${NC}"
echo ""
echo "预期输出："
echo "  成功：${GREEN}active [3]${NC}"
echo "  失败：${RED}inactive [2]${NC} 或 ${RED}unconfigured [1]${NC}"
echo ""
echo "查看可用的lifecycle服务："
echo -e "${YELLOW}ros2 service list | grep slam_toolbox${NC}"
echo ""
echo "应该显示："
echo "  /slam_toolbox/change_state"
echo "  /slam_toolbox/get_state"
echo "  ..."
echo ""
read -p "按回车键继续..."
echo ""

# 总结
echo "=========================================="
echo -e "${GREEN}测试完成！${NC}"
echo "=========================================="
echo ""
echo "检查清单："
echo ""
echo "基础功能："
echo "  [ ] 建图模式可以正常启动（10-15秒）"
echo "  [ ] 前端状态正确显示：切换中 → 就绪"
echo "  [ ] 控制台收到 mode_changed:mapping 消息"
echo ""
echo "超时处理："
echo "  [ ] SLAM配置有15秒超时（而不是5秒）"
echo "  [ ] 前端有20秒超时保护"
echo "  [ ] 超时后显示明确错误信息"
echo ""
echo "失败反馈："
echo "  [ ] 配置失败时前端显示'❌ 切换失败'"
echo "  [ ] 3秒后自动恢复到'✅ 就绪'"
echo "  [ ] 控制台显示详细错误原因"
echo ""
echo "调试信息："
echo "  [ ] 后端日志：'正在配置SLAM节点（可能需要10-15秒）...'"
echo "  [ ] 后端日志：'✅ SLAM配置成功' / '❌ SLAM配置失败'"
echo "  [ ] 后端日志：'已发布失败消息: mode_failed:...'"
echo "  [ ] 前端日志：'[导航调试] 收到导航信息: ...'"
echo ""
echo "时间验证："
echo "  成功情况："
echo "    - 后端配置：${GREEN}5-10秒${NC}"
echo "    - 前端等待：${GREEN}10-15秒${NC}"
echo "    - 总时长：${GREEN}<15秒${NC}"
echo ""
echo "  超时情况："
echo "    - 后端超时：${YELLOW}15秒${NC}"
echo "    - 前端超时：${YELLOW}20秒${NC}"
echo "    - 失败恢复：${YELLOW}3秒${NC}"
echo ""
echo "如果测试通过："
echo "  ${GREEN}✓${NC} SLAM可以正常启动"
echo "  ${GREEN}✓${NC} 超时时间合理"
echo "  ${GREEN}✓${NC} 失败反馈及时准确"
echo "  ${GREEN}✓${NC} 前端不会卡住"
echo ""
echo "如果仍有问题："
echo "  1. 检查SLAM配置文件（config/slam_toolbox.yaml）"
echo "  2. 查看完整的后端日志"
echo "  3. 查看浏览器控制台的完整日志"
echo "  4. 确认WebSocket连接正常（ws.readyState应该为1）"
echo "  5. 尝试手动启动SLAM："
echo "     ${YELLOW}ros2 lifecycle set /slam_toolbox configure${NC}"
echo "     ${YELLOW}ros2 lifecycle set /slam_toolbox activate${NC}"
echo ""
echo "详细文档："
echo "  - SLAM超时与状态反馈修复.md"
echo ""





