#!/bin/bash

echo "=========================================="
echo "摇杆0速度问题诊断测试"
echo "=========================================="
echo ""

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${YELLOW}问题描述${NC}"
echo "用户报告：摇杆保持稳定时，ROS话题中穿插0速度"
echo ""
echo -e "${YELLOW}本次改进${NC}"
echo "1. 添加死区（deadzone）过滤抖动"
echo "2. 添加详细调试信息追踪0速度来源"
echo "3. 监控drag事件频率"
echo ""

# 步骤1
echo -e "${BLUE}步骤1: 打开浏览器并强制刷新${NC}"
echo "=========================================="
echo "1. 打开：http://localhost:8080"
echo "2. ${RED}重要${NC}: 按 ${YELLOW}Ctrl + Shift + R${NC} 强制刷新（版本已更新到v5）"
echo "3. 按 ${YELLOW}F12${NC} 打开控制台"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤2
echo -e "${BLUE}步骤2: 在新终端监测ROS话题${NC}"
echo "=========================================="
echo "请打开一个新终端，运行："
echo ""
echo -e "${YELLOW}  ros2 topic echo /diff_drive_controller/cmd_vel${NC}"
echo ""
echo "或者只看频率："
echo ""
echo -e "${YELLOW}  ros2 topic hz /diff_drive_controller/cmd_vel${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤3
echo -e "${BLUE}步骤3: 测试摇杆稳定性${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 拖动摇杆到${YELLOW}正前方${NC}并保持不动"
echo "  2) 保持5-10秒"
echo "  3) 观察浏览器控制台和ROS话题"
echo ""
echo "预期的${GREEN}正常${NC}情况："
echo ""
echo "浏览器控制台应该显示："
echo "  ${GREEN}[摇杆调试] 开始拖拽, 摇杆启用: true, 导航模式: 0${NC}"
echo "  ${GREEN}[摇杆调试] 速度改变: (0.00, 0.00) -> (0.75, 0.00) [isDragging=true]${NC}"
echo "  ${GREEN}[摇杆调试] drag事件触发了200次，平均40.0次/秒${NC}  ← drag事件正常"
echo "  ${GREEN}[摇杆调试] 统计: 总50条, 非0:50条, 0:0条, ...${NC}  ← 没有0速度！"
echo ""
echo "ROS话题应该显示："
echo "  ${GREEN}持续的非0速度，无0速度穿插${NC}"
echo "  ${GREEN}linear.x: 约0.75-0.80${NC}"
echo "  ${GREEN}angular.z: 0或接近0（死区作用）${NC}"
echo ""
echo "如果出现${RED}异常${NC}："
echo "  ${RED}[摇杆调试] ⚠️ 发送0速度! isDragging=false, ...${NC}  ← 这是问题！"
echo "  ${RED}[摇杆调试] 结束拖拽 (事件:mouseleave), ...${NC}  ← 鼠标离开了窗口"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤4
echo -e "${BLUE}步骤4: 测试死区效果${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 拖动摇杆到${YELLOW}稍微偏左${NC}（很小的角度）"
echo "  2) 保持不动"
echo "  3) 观察angular速度"
echo ""
echo "预期结果："
echo "  如果偏移很小（<10%），angular应该被死区过滤为${GREEN}0${NC}"
echo "  如果偏移较大（>10%），angular应该显示${GREEN}非0值${NC}"
echo ""
echo "死区参数："
echo "  线速度死区: ±0.04 m/s (5%)"
echo "  角速度死区: ±0.20 rad/s (10%)"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤5
echo -e "${BLUE}步骤5: 测试松开摇杆${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 拖动摇杆"
echo "  2) 松开鼠标"
echo ""
echo "预期结果："
echo "  ${GREEN}[摇杆调试] 结束拖拽 (事件:mouseup), 发送停止命令${NC}"
echo "  ${GREEN}[摇杆调试] ⚠️ 发送0速度! isDragging=false, ...${NC}  ← 这是${GREEN}正常${NC}的"
echo "  ${GREEN}[摇杆调试] 速度改变: (0.75, 0.00) -> (0.00, 0.00) [isDragging=false]${NC}"
echo ""
echo "ROS话题应该显示："
echo "  ${GREEN}最后一条消息是0速度${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤6
echo -e "${BLUE}步骤6: 检查drag事件频率${NC}"
echo "=========================================="
echo ""
echo "在浏览器控制台，拖动摇杆并保持，观察："
echo "  ${GREEN}[摇杆调试] drag事件触发了XXX次，平均XX.X次/秒${NC}"
echo ""
echo "正常频率："
echo "  ${GREEN}30-60次/秒${NC} - 正常"
echo "  ${YELLOW}10-30次/秒${NC} - 可接受，但可能有性能问题"
echo "  ${RED}<10次/秒${NC} - 异常，drag事件丢失严重"
echo ""
echo "如果频率太低："
echo "  1. 检查CPU使用率（top命令）"
echo "  2. 关闭其他占用资源的程序"
echo "  3. 尝试不同的浏览器（Chrome, Firefox, Edge）"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤7
echo -e "${BLUE}步骤7: 高级诊断（如果问题仍存在）${NC}"
echo "=========================================="
echo ""
echo "在浏览器控制台输入以下命令查看详细状态："
echo ""
echo -e "${YELLOW}console.log({${NC}"
echo -e "${YELLOW}    isDragging,${NC}"
echo -e "${YELLOW}    currentLinear,${NC}"
echo -e "${YELLOW}    currentAngular,${NC}"
echo -e "${YELLOW}    lastSentLinear,${NC}"
echo -e "${YELLOW}    lastSentAngular,${NC}"
echo -e "${YELLOW}    cmdVelSendCount,${NC}"
echo -e "${YELLOW}    zeroVelSendCount,${NC}"
echo -e "${YELLOW}    nonZeroVelSendCount,${NC}"
echo -e "${YELLOW}    dragEventCount${NC}"
echo -e "${YELLOW}});${NC}"
echo ""
echo "录制ROS数据用于分析："
echo -e "${YELLOW}ros2 bag record /diff_drive_controller/cmd_vel${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 总结
echo "=========================================="
echo -e "${GREEN}测试完成！${NC}"
echo "=========================================="
echo ""
echo "检查清单："
echo ""
echo "基础功能："
echo "  [ ] 摇杆可以正常拖动"
echo "  [ ] 速度显示正确"
echo "  [ ] 松开后回到中心"
echo ""
echo "关键指标："
echo "  [ ] 保持摇杆时，${GREEN}无0速度穿插${NC}"
echo "  [ ] drag事件频率 ${GREEN}>30次/秒${NC}"
echo "  [ ] 0速度只在松开时出现"
echo "  [ ] 死区有效（小偏移被过滤为0）"
echo ""
echo "如果问题解决："
echo "  ${GREEN}✓${NC} ROS话题中无0速度穿插"
echo "  ${GREEN}✓${NC} 摇杆控制平滑稳定"
echo "  ${GREEN}✓${NC} 死区有效减少抖动"
echo ""
echo "如果问题仍存在："
echo "  1. 查看浏览器控制台的${RED}完整日志${NC}"
echo "  2. 特别注意${RED}\"⚠️ 发送0速度\"${NC}的警告"
echo "  3. 检查${RED}\"结束拖拽\"${NC}的触发原因"
echo "  4. 将日志和ROS话题数据发送给开发者"
echo ""
echo "详细文档："
echo "  - 摇杆0速度问题诊断.md"
echo ""




