#!/bin/bash

echo "=========================================="
echo "调试信息与状态反馈测试指南"
echo "=========================================="
echo ""

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}测试目标${NC}"
echo "1. 验证摇杆调试信息是否正常输出"
echo "2. 验证导航模式切换的成功/失败反馈"
echo ""

# 步骤1
echo -e "${YELLOW}步骤1: 打开浏览器并启用控制台${NC}"
echo "=========================================="
echo "1. 打开浏览器：http://localhost:8080"
echo "2. ${RED}重要${NC}: 按 ${YELLOW}Ctrl + Shift + R${NC} 强制刷新"
echo "3. 按 ${YELLOW}F12${NC} 打开开发者工具"
echo "4. 点击 ${YELLOW}Console${NC} 标签"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤2
echo -e "${YELLOW}步骤2: 测试摇杆调试信息${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 拖动摇杆到某个位置"
echo "  2) 保持几秒"
echo "  3) 松开摇杆"
echo ""
echo "预期在控制台看到："
echo "  ${GREEN}[摇杆调试] 开始拖拽, 摇杆启用: true, 导航模式: 0${NC}"
echo "  ${GREEN}[摇杆调试] 速度改变: (0.00, 0.00) -> (0.50, 0.20)${NC}"
echo "  ${GREEN}[摇杆调试] 已发送50条命令, WebSocket状态:1, ...${NC}"
echo "  ${GREEN}[摇杆调试] 结束拖拽, 发送停止命令${NC}"
echo "  ${GREEN}[摇杆调试] 速度改变: (0.50, 0.20) -> (0.00, 0.00)${NC}"
echo ""
echo "如果没有看到这些日志："
echo "  ${RED}✗${NC} 检查是否强制刷新了浏览器"
echo "  ${RED}✗${NC} 检查Console标签是否正确打开"
echo "  ${RED}✗${NC} 尝试清除浏览器缓存后重试"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤3
echo -e "${YELLOW}步骤3: 测试导航模式禁用摇杆${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 点击 ${YELLOW}\"导航\"${NC} 按钮（会失败，因为地图服务器未启动）"
echo "  2) 尝试拖动摇杆"
echo ""
echo "预期在控制台看到："
echo "  ${GREEN}[摇杆调试] 摇杆被禁用，当前模式: 2, 速度: 0.5 -0.3${NC}"
echo ""
echo "这是${GREEN}正常${NC}的，导航模式下摇杆应该被禁用"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤4
echo -e "${YELLOW}步骤4: 测试建图模式切换（成功）${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 切换回 ${YELLOW}\"手动\"${NC} 模式"
echo "  2) 点击 ${YELLOW}\"建图\"${NC} 按钮"
echo "  3) 观察状态显示"
echo ""
echo "预期结果："
echo "  ${GREEN}✓${NC} 状态显示：${YELLOW}⏳ 切换中...${NC} → ${GREEN}✅ 就绪${NC}"
echo "  ${GREEN}✓${NC} 日志显示：${GREEN}✅ 模式切换完成: mapping${NC}"
echo "  ${GREEN}✓${NC} 时间：1-2秒"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤5
echo -e "${YELLOW}步骤5: 测试导航模式切换（失败）${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) ${RED}不要${NC}启动地图服务器"
echo "  2) 点击 ${YELLOW}\"导航\"${NC} 按钮"
echo "  3) 观察状态显示"
echo ""
echo "预期结果："
echo "  ${GREEN}✓${NC} 状态显示：${YELLOW}⏳ 切换中...${NC} → ${RED}❌ 切换失败${NC}"
echo "  ${GREEN}✓${NC} 日志显示：${RED}❌ 模式切换失败: 地图服务器未启动,请先选择地图并启动地图服务器${NC}"
echo "  ${GREEN}✓${NC} 3秒后恢复：${GREEN}✅ 就绪${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤6
echo -e "${YELLOW}步骤6: 测试导航模式切换（成功）${NC}"
echo "=========================================="
echo ""
echo "操作："
echo "  1) 在地图管理模块选择一个地图"
echo "  2) 点击 ${YELLOW}\"▶️ 启动地图服务器\"${NC}"
echo "  3) 等待状态变为 ${GREEN}\"运行中\"${NC}"
echo "  4) 点击 ${YELLOW}\"导航\"${NC} 按钮"
echo "  5) 观察状态显示"
echo ""
echo "预期结果："
echo "  ${GREEN}✓${NC} 状态显示：${YELLOW}⏳ 切换中...${NC} → ${GREEN}✅ 就绪${NC}"
echo "  ${GREEN}✓${NC} 日志显示：${GREEN}✅ 模式切换完成: navigation${NC}"
echo "  ${GREEN}✓${NC} 时间：1-2秒"
echo "  ${GREEN}✓${NC} 摇杆被禁用"
echo ""
read -p "按回车键继续..."
echo ""

# 步骤7
echo -e "${YELLOW}步骤7: 高级调试（可选）${NC}"
echo "=========================================="
echo ""
echo "在浏览器控制台输入以下命令查看详细状态："
echo ""
echo -e "${BLUE}console.log({${NC}"
echo -e "${BLUE}    joystickEnabled,${NC}"
echo -e "${BLUE}    currentNavigationMode,${NC}"
echo -e "${BLUE}    isDragging,${NC}"
echo -e "${BLUE}    currentLinear,${NC}"
echo -e "${BLUE}    currentAngular,${NC}"
echo -e "${BLUE}    cmdVelSendCount,${NC}"
echo -e "${BLUE}    wsState: ws ? ws.readyState : null${NC}"
echo -e "${BLUE}});${NC}"
echo ""
echo "同时在终端监测ROS话题："
echo ""
echo -e "${BLUE}ros2 topic echo /diff_drive_controller/cmd_vel${NC}"
echo -e "${BLUE}ros2 topic hz /diff_drive_controller/cmd_vel${NC}"
echo -e "${BLUE}ros2 topic echo /navigation/info${NC}"
echo ""
read -p "按回车键继续..."
echo ""

# 总结
echo "=========================================="
echo -e "${GREEN}测试完成！${NC}"
echo "=========================================="
echo ""
echo "检查清单："
echo ""
echo "摇杆调试信息："
echo "  [ ] 拖拽开始/结束有日志"
echo "  [ ] 速度改变有日志"
echo "  [ ] 每5秒有统计信息"
echo "  [ ] 导航模式禁用有警告"
echo ""
echo "状态反馈："
echo "  [ ] 建图模式切换成功显示\"就绪\""
echo "  [ ] 导航模式切换失败显示\"切换失败\""
echo "  [ ] 导航模式切换成功显示\"就绪\""
echo "  [ ] 错误消息清晰明确"
echo ""
echo "如果所有测试通过："
echo "  ${GREEN}✓${NC} 调试信息完善，便于排查问题"
echo "  ${GREEN}✓${NC} 状态反馈清晰，用户体验好"
echo ""
echo "如果有问题，请查看："
echo "  - 浏览器控制台的完整输出"
echo "  - ROS终端的日志信息"
echo "  - 调试信息与状态反馈完善.md"
echo ""

